### ISSUE TITLE
Could theme be pushed to the VSX open registry?

### ISSUE THREAD

**Issue by chic-geek** [MateoCerquetella/xcode-theme#10]
**Is your feature request related to a problem? Please describe.**
I'm making use of Gitpod.io and I can't install the xcode-theme as it'll break Microsoft's Terms of License.

**Describe the solution you'd like**
Could this be uploaded to the VSX Open Registry please so I can continue to use this theme.

**Describe alternatives you've considered**
Tried using other Xcode themes that are available but just not as nice =)

**Additional context**
N/A

**Comment by MateoCerquetella** [comment]
Hi @chic-geek, Sure! I will try to upload the theme today

**Comment by MateoCerquetella** [comment]
Here it is: https://open-vsx.org/extension/mateocerquetella/xcode-12-theme 

If you like the theme I will be pleased if you give me a rating in the vscode marketplace 😄
