### ISSUE TITLE
Improve theme for dart support in flutter

### ISSUE THREAD

**Issue by MisterLight** [MateoCerquetella/xcode-theme#12]
Coming from SwiftUI I started recently to use flutter in VSCode, love color scheme from XCode but in VSCode looks some tiny things are weird to me. Check the image bellow

<img width="689" alt="Captura de pantalla 2023-04-22 a las 18 25 15" src="https://user-images.githubusercontent.com/46331533/233795993-73d1d0bb-dd05-4925-bcca-aba595bee80d.png">

And how you see code in SwiftUI

<img width="538" alt="image" src="https://user-images.githubusercontent.com/46331533/233796146-97a969db-459f-4f2b-851b-0cd451e47c75.png">

In VSCode variables and functions calls have same color, can you change that? 
Thank you

**Comment by MateoCerquetella** [comment]
Hi @MisterLight, yes I can help you with this when I have some time over the weekend 👍🏻

**Comment by MateoCerquetella** [comment]
Hi @MisterLight, I had some time to review this and I understand your concern about the color scheme differences between SwiftUI and Flutter in VSCode. The reason for this difference is that they are two distinct languages, each with its own syntax and structure. SwiftUI is a framework for Swift, while Flutter uses the Dart programming language.

The color scheme you are using in VSCode is currently designed to highlight specific syntax elements based on their respective languages. If you'd like to have more distinct colors for variables and function calls in Flutter, I can suggest to you to modifying the theme to better suit your preferences.

For example, you can update the existing theme by adding these rules to the tokenColors array in your settings.json:

```javascript
{
  ...
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["entity.name.function.flutter"],
        "settings": {
          "foreground": "#5DD8FF"
        }
      },
      {
        "scope": ["variable.parameter.flutter"],
        "settings": {
          "foreground": "#83C9BC"
        }
      }
    ]
  },
  ...
}
``` 
In my last update I added Dart language support (https://github.com/MateoCerquetella/xcode-theme/issues/8), but please  feel free to let me know if you have any other questions, suggestion or need further assistance.

**Comment by MisterLight** [comment]
Hi @MateoCerquetella, thank you for your response. I didn't know nothing about the "tokenColorCustomizations" property, so, I use your example and googling a bit I finally set a color scheme that I really like for vscode.

I send a screenshot, as reference too, in case someone want to do the same.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/46331533/234397307-d59f6a4b-ea73-462b-82b3-a06ad6cbb1ef.png">
