### ISSUE TITLE
Port Spartan, Low Key, and Civic from Xcode?

### ISSUE THREAD

**Issue by ascarter** [MateoCerquetella/xcode-theme#13]
Great themes - match pretty well with Xcode. Any interest in porting over Civic, Spartan, and Low Key as well? I use Spartan or Low Key usually for day and Civic at night.

Thanks!

**Comment by MateoCerquetella** [comment]
Hi Andrew,

Absolutely, I can get Low Key and Civic ported over. However, I don’t have any specifics on Spartan in my Xcode themes. If you could provide some details or a reference, that'd be helpful.

Thanks!

**Comment by MateoCerquetella** [comment]
@ascarter Civic almost done
<img width="1792" alt="Screenshot 2023-11-02 at 1 20 13 PM" src="https://github.com/MateoCerquetella/xcode-theme/assets/33433649/f7145697-bca6-40a4-be24-47708e34f6b3">

**Comment by MateoCerquetella** [comment]
Hi @ascarter,

I've completed porting Low Key and Civic. However, I'm lacking information on Spartan. If you could share some details or a reference, I'd be glad to get that sorted too.

Thanks 😄

**Comment by ascarter** [comment]
Spartan is built-in to Xcode. If you don't have it, try hitting the **+** in the Themes dialog and you should see them as "New From Template"

<img width="1739" alt="Screenshot 2023-11-08 at 9 49 27 AM" src="https://github.com/MateoCerquetella/xcode-theme/assets/4931/dd5c3c58-d872-4296-98b7-b02ab2cf4f11">

**Comment by MateoCerquetella** [comment]
Hi @ascarter,

All themes, including Low Key, Civic, and Spartan, are now live in production. Feel free to check them out. Also, if you're satisfied with the work, a 5-star rating would be greatly appreciated!

I'm going to close this PR, but feel free to reopen it if there's anything else you'd like to discuss.

Thanks 😄
