### ISSUE TITLE
How do I get a file icon theme on  the example image?

### ISSUE THREAD

**Issue by dongjb** [MateoCerquetella/xcode-theme#14]
![68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d766965772669643d3171645047796d5f375276586f2d674679525537337a70765a646c334a7a614b42](https://github.com/MateoCerquetella/xcode-theme/assets/33796081/9206cb28-d18b-44af-a0c0-e97651d3bdc1)

Thanks!!!

**Comment by MateoCerquetella** [comment]
Hi @dongjb , the extension theme of the folder is this:
https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons

Thanks!
