### ISSUE TITLE
Semantic Highlighting support

### ISSUE THREAD

**Issue by DavidGoldman** [MateoCerquetella/xcode-theme#2]
Xcode has semantic highlighting supporting, coloring tokens based on their semantic meaning (e.g. type vs method vs system library)

**Describe the solution you'd like**
Similar semantic coloring to what you see inside of Xcode. There's [this VS Code guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming) which summarizes how themes can implement this. Would contributions be welcome?

**Comment by MateoCerquetella** [comment]
Hi David!
Of course, every contribution who can help the project are welcome as well new suggestions
