### ISSUE TITLE
Thoughts on tab color suggestions?

### ISSUE THREAD

**Issue by jathu** [MateoCerquetella/xcode-theme#3]
Hi, thanks for creating this theme. I love it so far! 

One of the issues I have is getting confused about which tab is open. Most VS Code theme active tabs have the same color as the editor's background color. What are your thoughts on these changes?
![Screen Shot 2021-10-28 at 1 32 04 PM](https://user-images.githubusercontent.com/4391247/139332547-c8d7b9d7-cc70-4258-889c-fd960fad8209.png)

Also, how did you create this theme? Did you manually create it or use a tool? Thanks!

**Comment by MateoCerquetella** [comment]
Hi @jathu,

Nicely done with the recommendations, 
<img width="1648" alt="Screen Shot 2021-10-28 at 10 00 53 PM" src="https://user-images.githubusercontent.com/33433649/139356264-871361ee-883a-453e-acf8-5a7c02ef1727.png">

I created this theme manually, I think I cloned an existing one and then started making changes, feel free to do it aswell,

Gonna do a release in a few hours with the new changes!

**Comment by jathu** [comment]
@MateoCerquetella I love it 😍 ! Thank you so much for considering and updating it!
