### ISSUE TITLE
How about the light theme

### ISSUE THREAD

**Issue by bboysnick5** [MateoCerquetella/xcode-theme#4]
Hey, really nice work. Any idea if you can port the light theme as well. Basically what i'm expecting are font weight and font style as well as highlighting colors. Thanks.

**Comment by MateoCerquetella** [comment]
Hey @bboysnick5 thanks for your feedback! Of course, I was thinking to do the light theme version on the future but now that your ask for it I will start right away. Also if you can give 5 stars to the extension on the VSCode market I will really appreciate it!

**Comment by MateoCerquetella** [comment]
@bboysnick5 you are welcome to contribute alwell!
