### ISSUE TITLE
Git Indicators

### ISSUE THREAD

**Issue by heebeejeebees** [MateoCerquetella/xcode-theme#5]
**Git Indicators**
For filenames on the explorer panel and tabs, there are red, orange, and gray indicators but the green is missing. 

**Additional**
For the theme "Xcode Default Dark Customized Version", the comments color is too similar to the selecting/highlighting color. Selecting comments practically hides them. Love the darker background for this theme. 

PS: I have rated you 5 stars on VSCode Marketplace, I am using it on the daily! Thanks for the great work.

**Comment by MateoCerquetella** [comment]
Hi @heebeejeebees, thanks for reporting this, I would look into that shortly.

**Comment by heebeejeebees** [comment]
Thank you for your time! The semicolons for all themes have pretty low visibility as well actually

**Comment by MateoCerquetella** [comment]
Yeah it was added on purpose to get more clarity on the actual code =)

**Comment by MateoCerquetella** [comment]
I will close this issue as I will continue the development when I got time, thanks for the suggestions and remember you can fork and help me with this making an MR.

Regards, Mateo
