### ISSUE TITLE
can you please add DART  flutter langauge support

### ISSUE THREAD

**Issue by fisforfaheem** [MateoCerquetella/xcode-theme#8]
it would lbe loved

**Comment by MateoCerquetella** [comment]
Yeah, I will try this weekend when I have some spare time

**Comment by fisforfaheem** [comment]
Thanks, much appreciated

**Comment by MateoCerquetella** [comment]
@fisforfaheem is this good for you? any correction that you would do?
<img width="812" alt="Screenshot 2022-12-16 at 10 59 28 AM" src="https://user-images.githubusercontent.com/33433649/208114218-1770cc0f-b349-4fb8-a15b-8f7c5d9bda7c.png">

**Comment by fisforfaheem** [comment]
Amazing, 😍 thank you. This will do it.. however do give a look to monokai
pro theme a bit as well for some inspiration
